FROM ubuntu:24.04
LABEL org.opencontainers.image.authors="Ethan Blanton <eblanton@buffalo.edu>"

# Josh Caskie made updates to this image in Spring 2023, but is no
# longer a maintainer.

#Utilities and Updates
RUN apt-get update --fix-missing

RUN apt-get install -y gcc
RUN apt-get install -y g++
RUN apt-get install -y make 
RUN apt-get install -y wget
RUN apt-get install -y gawk 
RUN apt-get install -y python3


#Golang Setup
ARG GOVERSION=1.23.12
RUN wget https://go.dev/dl/go$GOVERSION.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go$GOVERSION.linux-amd64.tar.gz
# Update the PATH manually within the image setup
ENV PATH="$PATH:/usr/local/go/bin"

# Install autodriver
WORKDIR /home
RUN useradd autolab
RUN useradd autograde
RUN mkdir autolab autograde output
RUN chown autolab:autolab autolab
RUN chown autolab:autolab output
RUN chown autograde:autograde autograde
RUN apt-get update && apt-get install -y sudo 
RUN apt-get install -y git
RUN git clone https://github.com/UBAutograding/Tango.git
WORKDIR Tango/autodriver
RUN make clean && make
RUN cp autodriver /usr/bin/autodriver
RUN chmod +s /usr/bin/autodriver

# Clean up
WORKDIR /home
RUN apt-get -y autoremove
RUN rm -rf Tango/

# Check installation
RUN ls -l /home
RUN which autodriver
RUN go version


# Used for testing Go version upon "docker run <image>"
# CMD go version
